version: 2

project_name: ghostport

before:
  hooks:
    - go mod tidy

builds:
  - id: ghostport
    main: .
    binary: ghostport
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: ghostport
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - name: ghostport
    repository:
      owner: mubashirtaj
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: "https://github.com/mubashirtaj/ghostport"
    description: "Explains and kills whatever is using a local port."
    license: "MIT"
    install: |
      bin.install "ghostport"
    test: |
      system "#{bin}/ghostport", "--version"

release:
  github:
    owner: mubashirtaj
    name: ghostport
  draft: false
  prerelease: auto
